const constants = {
  UPLOAD_PATH: "uploads/",

  /* Files Path Constants */
  COMPANY_LOGO_IMG_FOLDER: "companies/logo/",
  COMPANY_SIGN_IMG_FOLDER: "companies/signatures/",
  USER_IMG_FOLDER: "users/images/",
  USER_SIGN_IMG_FOLDER: "users/signatures/",
  ATTACHMENT_FOLDER: "attachments/",
  SIGNATURE_FOLDER: "signature/",
  ATTENDANCE_FOLDER: "employee/attendance/",
  ATTENDANCE_LOG_FOLDER: "employee/attendance_log/",
  EMPLOYEE_DOC_FOLDER: "employee/docs/",
  EMPLOYEE_IMG_FOLDER: "employee/images/",

  /* =======================
   * COMMON / GENERIC
   * ======================= */
  SUCCESS: "SUCCESS",
  CREATED: "CREATED",
  UPDATED: "UPDATED",
  DELETED: "DELETED",
  FETCHED: "FETCHED",
  REQUIRED: "REQUIRED",
  NO_RECORDS_FOUND: "NO_RECORDS_FOUND",
  ACTION_SUCCESSFUL: "ACTION_SUCCESSFUL",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  OTP_LIMIT_INFO: "OTP_LIMIT_INFO",
  BLOCKED_NUMBERS_LIST: "BLOCKED_NUMBERS_LIST",
  INTERNAL_DB_ERROR: "INTERNAL_DB_ERROR",

  /* =======================
   * VALIDATION & INPUT
   * ======================= */
  VALIDATION_ERROR: "VALIDATION_ERROR",
  REQUIRED_FIELD_MISSING: "REQUIRED_FIELD_MISSING",
  INVALID_INPUT: "INVALID_INPUT",
  INVALID_FIELD_NAME: "INVALID_FIELD_NAME",
  INVALID_ID: "INVALID_ID",
  INVALID_STATUS: "INVALID_STATUS",
  DATE_FORMAT_INVALID: "DATE_FORMAT_INVALID",
  INVALID_FILE_FORMAT: "INVALID_FILE_FORMAT",
  FILE_NOT_FOUND: "FILE_NOT_FOUND",
  SELECT_AT_LEAST_ONE_RECORD: "SELECT_AT_LEAST_ONE_RECORD",
  ATLEAST_ONE_ITEM_REQUIRED: "ATLEAST_ONE_ITEM_REQUIRED",
  AT_LEAST_ONE_TAX: "AT_LEAST_ONE_TAX",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  ACCOUNT_ALREADY_ACTIVE: "ACCOUNT_ALREADY_ACTIVE",



  /* =======================
   * AUTH & PERMISSION
   * ======================= */
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  PASSWORD_MISMATCH: "PASSWORD_MISMATCH",
  OLD_PASSWORD_INCORRECT: "OLD_PASSWORD_INCORRECT",
  INVALID_STAFF_ENUM: "INVALID_STAFF_ENUM",
  INVALID_SALARY_ENUM: "INVALID_SALARY_ENUM",

  /* =======================
  * PERMISSION / MIDDLEWARE
  * ======================= */
  USER_INACTIVE: "USER_INACTIVE",
  NO_PERMISSIONS_ASSIGNED: "NO_PERMISSIONS_ASSIGNED",
  ENTITYNOT_FOUND: "ENTITYNOT_FOUND",
  PERMISSION_CONFIG_MISSING: "PERMISSION_CONFIG_MISSING", // For missing permission types
  COMPANY_OR_BRANCH_MISSING: "COMPANY_OR_BRANCH_MISSING",
  PERMISSION_DENIED_DETAIL: "PERMISSION_DENIED_DETAIL",

  /* =======================
   * RESOURCE / DATA
   * ======================= */
  NOT_FOUND: "NOT_FOUND",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  ALREADY_DELETED: "ALREADY_DELETED",
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",
  FOREIGN_KEY_CONSTRAINT: "FOREIGN_KEY_CONSTRAINT",

  /* =======================
   * DATABASE / SERVER
   * ======================= */
  DATABASE_ERROR: "DATABASE_ERROR",
  TRANSACTION_FAILED: "TRANSACTION_FAILED",
  SERVER_ERROR: "SERVER_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  FAILED_TO_CREATE_RECORD: "FAILED_TO_CREATE_RECORD",
  FAILED_TO_UPDATE_RECORD: "FAILED_TO_UPDATE_RECORD",
  FAILED_TO_DELETE_RECORD: "FAILED_TO_DELETE_RECORD",
  FAILED_TO_CREATE_STOCK: "FAILED_TO_CREATE_STOCK",
  FAILED_TO_UPDATE_STOCK: "FAILED_TO_UPDATE_STOCK",
  FAILED_TO_DELETE_STOCK: "FAILED_TO_DELETE_STOCK",
  FAILED_TO_APPROVE_STOCK: "FAILED_TO_APPROVE_STOCK",
  STOCK_GENERAL_ID_REQUIRED: "STOCK_GENERAL_ID_REQUIRED",
  RESERVE_ADD_STOCK_DELETED: "RESERVE_ADD_STOCK_DELETED",

  /* =======================
   * FILE / UPLOAD
   * ======================= */
  FILE_REQUIRED: "FILE_REQUIRED",
  FILE_TYPE_NOT_ALLOWED: "FILE_TYPE_NOT_ALLOWED",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",

  /* =======================
   * EMAIL
   * ======================= */
  EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",
  EMAIL_AUTH_FAILED: "EMAIL_AUTH_FAILED",
  EMAIL_CONNECTION_FAILED: "EMAIL_CONNECTION_FAILED",
  EMAIL_TIMEOUT: "EMAIL_TIMEOUT",

  /* =======================
   * BUSINESS RULES
   * ======================= */
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  NEGATIVE_STOCK_NOT_ALLOWED: "NEGATIVE_STOCK_NOT_ALLOWED",
  STOCK_NOT_AVAILABLE: "STOCK_NOT_AVAILABLE",
  SERIES_NOT_FOUND: "SERIES_NOT_FOUND",
  SERIES_EXHAUSTED: "SERIES_EXHAUSTED",

  /* =======================
   * ACCOUNTS
   * ======================= */

  COUNTRY_MASTER_CREATED: "COUNTRY_MASTER_CREATED",
  COUNTRY_MASTER_UPDATED: "COUNTRY_MASTER_UPDATED",
  COUNTRY_MASTER_DELETED: "COUNTRY_MASTER_DELETED",
  COUNTRY_MASTER_NOT_FOUND: "COUNTRY_MASTER_NOT_FOUND",

  STATE_MASTER_CREATED: "STATE_MASTER_CREATED",
  STATE_MASTER_UPDATED: "STATE_MASTER_UPDATED",
  STATE_MASTER_DELETED: "STATE_MASTER_DELETED",
  STATE_MASTER_NOT_FOUND: "STATE_MASTER_NOT_FOUND",

  CURRENCY_MASTER_CREATED: "CURRENCY_MASTER_CREATED",
  CURRENCY_MASTER_UPDATED: "CURRENCY_MASTER_UPDATED",
  CURRENCY_MASTER_DELETED: "CURRENCY_MASTER_DELETED",
  CURRENCY_MASTER_NOT_FOUND: "CURRENCY_MASTER_NOT_FOUND",

  LOGIN_HISTORY_CREATED: "LOGIN_HISTORY_CREATED",
  LOGIN_HISTORY_UPDATED: "LOGIN_HISTORY_UPDATED",
  LOGIN_HISTORY_DELETED: "LOGIN_HISTORY_DELETED",
  LOGIN_HISTORY_NOT_FOUND: "LOGIN_HISTORY_NOT_FOUND",

  // Holiday
  HOLIDAY_CREATED: "HOLIDAY_CREATED",
  HOLIDAY_UPDATED: "HOLIDAY_UPDATED",
  HOLIDAY_DELETED: "HOLIDAY_DELETED",
  HOLIDAY_NOT_FOUND: "HOLIDAY_NOT_FOUND",

  // Holiday Template
  HOLIDAY_TEMPLATE_CREATED: "HOLIDAY_TEMPLATE_CREATED",
  HOLIDAY_TEMPLATE_UPDATED: "HOLIDAY_TEMPLATE_UPDATED",
  HOLIDAY_TEMPLATE_DELETED: "HOLIDAY_TEMPLATE_DELETED",
  HOLIDAY_TEMPLATE_NOT_FOUND: "HOLIDAY_TEMPLATE_NOT_FOUND",

  // Holiday Transaction
  HOLIDAY_TRANSACTION_CREATED: "HOLIDAY_TRANSACTION_CREATED",
  HOLIDAY_TRANSACTION_UPDATED: "HOLIDAY_TRANSACTION_UPDATED",
  HOLIDAY_TRANSACTION_DELETED: "HOLIDAY_TRANSACTION_DELETED",
  HOLIDAY_TRANSACTION_NOT_FOUND: "HOLIDAY_TRANSACTION_NOT_FOUND",

  // Employee
  EMPLOYEE_CREATED: "EMPLOYEE_CREATED",
  EMPLOYEE_UPDATED: "EMPLOYEE_UPDATED",
  EMPLOYEE_DELETED: "EMPLOYEE_DELETED",
  EMPLOYEE_DATA_IS_REQUIRED_AND_MUST_BE_AN_ARRAY: "EMPLOYEE_DATA_IS_REQUIRED_AND_MUST_BE_AN_ARRAY",

  // Salary Template
  SALARY_TEMPLATE_CREATED: "SALARY_TEMPLATE_CREATED",
  SALARY_TEMPLATE_UPDATED: "SALARY_TEMPLATE_UPDATED",
  SALARY_TEMPLATE_DELETED: "SALARY_TEMPLATE_DELETED",

  /* =======================
   * ADMINISTRATION
   * ======================= */

  // Role & Permission
  ROLE_PERMISSION_CREATED: "ROLE_PERMISSION_CREATED",
  ROLE_PERMISSION_UPDATED: "ROLE_PERMISSION_UPDATED",
  ROLE_PERMISSION_DELETED: "ROLE_PERMISSION_DELETED",
  ROLE_PERMISSION_NOT_FOUND: "ROLE_PERMISSION_NOT_FOUND",

  // Company Bank (Accounts)
  COMPANY_BANK_CREATED: "COMPANY_BANK_CREATED",
  COMPANY_BANK_UPDATED: "COMPANY_BANK_UPDATED",
  COMPANY_BANK_DELETED: "COMPANY_BANK_DELETED",
  COMPANY_BANK_NOT_FOUND: "COMPANY_BANK_NOT_FOUND",

  // Companies
  COMPANY_CREATED: "COMPANY_CREATED",
  COMPANY_UPDATED: "COMPANY_UPDATED",
  COMPANY_DELETED: "COMPANY_DELETED",
  COMPANY_NOT_FOUND: "COMPANY_NOT_FOUND",

  PARTIES_CREATED: "PARTIES_CREATED",
  PARTIES_UPDATED: "PARTIES_UPDATED",
  PARTIES_DELETED: "PARTIES_DELETED",
  PARTIES_NOT_FOUND: "PARTIES_NOT_FOUND",

  COMPANY_SETTING_MASTER_CREATED: "COMPANY_SETTING_MASTER_CREATED",
  COMPANY_SETTING_MASTER_UPDATED: "COMPANY_SETTING_MASTER_UPDATED",
  COMPANY_SETTING_MASTER_DELETED: "COMPANY_SETTING_MASTER_DELETED",
  COMPANY_SETTING_MASTER_NOT_FOUND: "COMPANY_SETTING_MASTER_NOT_FOUND",

  // Validation messages
  ACCOUNT_NUMBER_MISMATCH: "ACCOUNT_NUMBER_MISMATCH",

  // Company Bank (Accounts)
  BANK_CREATED: "BANK_CREATED",
  BANK_UPDATED: "BANK_UPDATED",
  BANK_DELETED: "BANK_DELETED",
  BANK_NOT_FOUND: "BANK_NOT_FOUND",

  // STATUTORY_LWF_RULE_MASTER
  STATUTORY_LWF_RULE_MASTER_CREATED: "STATUTORY_LWF_RULE_MASTER_CREATED",
  STATUTORY_LWF_RULE_MASTER_UPDATED: "STATUTORY_LWF_RULE_MASTER_UPDATED",
  STATUTORY_LWF_RULE_MASTER_DELETED: "STATUTORY_LWF_RULE_MASTER_DELETED",
  STATUTORY_LWF_RULE_MASTER_NOT_FOUND: "STATUTORY_LWF_RULE_MASTER_NOT_FOUND",

  //STATUTORY_PTR_RULE_MASTER
  STATUTORY_PTR_RULE_MASTER_CREATED: "STATUTORY_PTR_RULE_MASTER_CREATED",
  STATUTORY_PTR_RULE_MASTER_UPDATED: "STATUTORY_PTR_RULE_MASTER_UPDATED",
  STATUTORY_PTR_RULE_MASTER_DELETED: "STATUTORY_PTR_RULE_MASTER_DELETED",
  STATUTORY_PTR_RULE_MASTER_NOT_FOUND: "STATUTORY_PTR_RULE_MASTER_NOT_FOUND",

  /* =======================
   * USER / COMPANY LIMITS
  * ======================= */
  LIMIT_EXCEEDED: "LIMIT_EXCEEDED",
  USER_LIMIT_REACHED: "USER_LIMIT_REACHED",
  COMPANY_LIMIT_REACHED: "COMPANY_LIMIT_REACHED",
  ENTITY_CREATED: "ENTITY_CREATED",
  ENTITY_UPDATED: "ENTITY_UPDATED",
  ENTITY_DELETED: "ENTITY_DELETED",
  MODULE_CREATED: "MODULE_CREATED",
  MODULE_UPDATED: "MODULE_UPDATED",
  MODULE_DELETED: "MODULE_DELETED",
  MODULE_PERMISSION_TYPE_CREATED: "MODULE_PERMISSION_TYPE_CREATED",
  MODULE_PERMISSION_TYPE_UPDATED: "MODULE_PERMISSION_TYPE_UPDATED",
  MODULE_PERMISSION_TYPE_DELETED: "MODULE_PERMISSION_TYPE_DELETED",
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_DELETED: "USER_DELETED",

  /* =======================
   * SHIFT / ATTENDANCE
   * ======================= */
  SHIFT_CREATED: "SHIFT_CREATED",
  SHIFT_UPDATED: "SHIFT_UPDATED",
  SHIFT_DELETED: "SHIFT_DELETED",

  /* =============================
   * SETTINGS / WEEKLYOFFTEMPLATE
   * ============================= */
  WEEKLY_OFF_CREATED: "WEEKLY_OFF_CREATED",
  WEEKLY_OFF_UPDATED: "WEEKLY_OFF_UPDATED",
  WEEKLY_OFF_DELETED: "WEEKLY_OFF_DELETED",

  /* =============================
   * SETTINGS / DEVICEMASTER
   * ============================= */
  DEVICE_MASTER_CREATED: "DEVICE_MASTER_CREATED",
  DEVICE_MASTER_UPDATED: "DEVICE_MASTER_UPDATED",
  DEVICE_MASTER_DELETED: "DEVICE_MASTER_DELETED",

  /* =============================
   * SETTINGS / DESIGNATIONMASTER
   * ============================= */
  DESIGNATION_MASTER_CREATED: "DESIGNATION_MASTER_CREATED",
  DESIGNATION_MASTER_UPDATED: "DESIGNATION_MASTER_UPDATED",
  DESIGNATION_MASTER_DELETED: "DESIGNATION_MASTER_DELETED",

  
  /* =============================
   * SETTINGS / DEPARTMENT
   * ============================= */
  DEPARTMENT_MASTER_CREATED: "DEPARTMENT_MASTER_CREATED",
  DEPARTMENT_MASTER_UPDATED: "DEPARTMENT_MASTER_UPDATED",
  DEPARTMENT_MASTER_DELETED: "DEPARTMENT_MASTER_DELETED",


  /* =============================
   * SETTINGS / ATTENDANCETEMPLATE
   * ============================= */
  ATTENDANCE_TEMPLATE_CREATED: "ATTENDANCE_TEMPLATE_CREATED",
  ATTENDANCE_TEMPLATE_UPDATED: "ATTENDANCE_TEMPLATE_UPDATED",
  ATTENDANCE_TEMPLATE_DELETED: "ATTENDANCE_TEMPLATE_DELETED",

  /* =======================
  * LEAVE TEMPLATE
  * ======================= */
  LEAVE_TEMPLATE_CREATED: "LEAVE_TEMPLATE_CREATED",
  LEAVE_TEMPLATE_UPDATED: "LEAVE_TEMPLATE_UPDATED",
  LEAVE_TEMPLATE_DELETED: "LEAVE_TEMPLATE_DELETED",

  // Attendance
  ATTENDANCE_CREATED: "ATTENDANCE_CREATED",
  ATTENDANCE_UPDATED: "ATTENDANCE_UPDATED",
  ATTENDANCE_FETCHED: "ATTENDANCE_FETCHED",
  ATTENDANCE_DELETED: "ATTENDANCE_DELETED",
  ATTENDANCE_NOT_FOUND: "ATTENDANCE_NOT_FOUND",
};

const ENTITIES = {
  ITEM_MASTER: { ID: 17, NAME: "Item" },
  PARTIES_MASTER: { ID: 27, NAME: "Party" },
  COMPANY_MASTER: { ID: 33, NAME: "Company" },
  BRANCH_MASTER: { ID: 14, NAME: "Branch" },
  USER: { ID: 1, NAME: "User" },
  DRAWING_MASTER: { ID: 37, NAME: "Drawing" },
  PROCESS_LIST_MASTER: { ID: 19, NAME: "ProcessList" },
  RESOURCE_MASTER: { ID: 21, NAME: "Resource" },
  GODOWN: { ID: 48, NAME: "Godown" },

  ITEM_TYPE_MASTER: { ID: 25, NAME: "ItemType" },
  ITEM_CATEGORY: { ID: 15, NAME: "ItemCategory" },
  ITEM_UNIT_MASTER: { ID: 26, NAME: "ItemUnit" },
  ITEM_NAME_PARAMETER: { ID: 8, NAME: "ItemNameParameter" },
  ITEM_SPEC_MASTER: { ID: 12, NAME: "ItemSpecification" },
  ITEM_SPEC_VALUE: { ID: 999, NAME: "ItemSpecificationValue" },
  HSN_MASTER: { ID: 18, NAME: "HSN" },
  QC_PARAMETER: { ID: 20, NAME: "QcParameter" },

  PARTIES_GROUP: { ID: 100, NAME: "PartiesGroup" },
  PARTIES_ADDRESS: { ID: 101, NAME: "PartiesAddress" },
  PARTIES_CONTACT: { ID: 102, NAME: "PartiesContacts" },
  PARTIES_CONSIGNEE: { ID: 103, NAME: "PartiesConsignee" },
  PARTIES_BANK: { ID: 104, NAME: "PartiesBank" },

  SERIES_TYPE: { ID: 105, NAME: "SeriesType" },
  DOCUMENT_MASTER: { ID: 106, NAME: "Document" },
  BUSINESS_TYPE: { ID: 107, NAME: "BusinessType" },
  COMMON_CATEGORY: { ID: 108, NAME: "CommonCategory" },
  PAYMENT_TERMS: { ID: 109, NAME: "PaymentTerms" },
  TRANSPORT_MASTER: { ID: 24, NAME: "Transpotation" },
  BANK_MASTER: { ID: 13, NAME: "Bank" },
  COUNTRY_MASTER: { ID: 110, NAME: "Country" },
  STATE_MASTER: { ID: 111, NAME: "State" },
  CITY_MASTER: { ID: 112, NAME: "City" },
  ZONE_MASTER: { ID: 113, NAME: "Zone" },
  CURRENCY_MASTER: { ID: 16, NAME: "Currency" },
  ROLE_PERMISSION: { ID: 10, NAME: "RolePermission" },

  TAX_TYPE: { ID: 34, NAME: "TaxType" },
  TAX: { ID: 115, NAME: "Taxes" },
  TAX_GROUP: { ID: 35, NAME: "TaxGroup" },
  CHARGES: { ID: 36, NAME: "Charges" },
  TERMS_MASTER: { ID: 23, NAME: "Terms" },

  SALES: { ID: 2, NAME: "Sales" },
  LEADS: { ID: 1, NAME: "leads" },
  QUOTATION: { ID: 3, NAME: "Quotation" },
  PROFORMA: { ID: 41, NAME: "ProformaInvoice" },
  TASK: { ID: 31, NAME: "Task" },

  STOCK_GENERAL: { ID: 55, NAME: "StockGeneral" },
  BATCH_STOCK: { ID: 56, NAME: "BatchStockIn" },

  INVOICE: { ID: 39, NAME: "Invoice" },
  GENERAL_BOOK: { ID: 200, NAME: "GeneralBook" },

  INDENT: { ID: 300, NAME: "Indent" },
  INDENT_APPROVAL: { ID: 300, NAME: "INDENT_APPROVAL" },
  PURCHASE_ORDER: { ID: 38, NAME: "PurchaseOrder" },
  PURCHASE_BILL: { ID: 38, NAME: "PURCHASE_BILL" },
  PURCHASE_QUOTATION: { ID: 38, NAME: "PURCHASE_QUOTATION" },
  QUOTATION_TRANSACTION: { ID: 38, NAME: "QUOTATION_TRANSACTION" },
  QUOTATION_COMPARISON: { ID: 301, NAME: "QuotationComparisonRequest" },

  BOM: { ID: 52, NAME: "BOM" },
  ITEM_BOM_VERSION: { ID: 53, NAME: "ItemBomVersion" },
  PRODUCT_BOM_VERSION: { ID: 54, NAME: "ProductBomVersion" },

  DISPATCH: { ID: 49, NAME: "DeliveryChallan" },

  ACTIVITY_LOG: { ID: 400, NAME: "ActivityLog" },
  LOGIN_HISTORY: { ID: 401, NAME: "LoginHistory" },
  COMPANY_CONFIGRATION: { ID: 401, NAME: "CompanyConfigration" },
  COMPANY_BANK: { ID: 401, NAME: "CompanyBank" },
  STAGE: { ID: 401, NAME: "Stage" },

  SIGNATURE: { ID: 55, NAME: "Signature" },
  SIGNATURE_CREATED: "SIGNATURE_CREATED",
  SIGNATURE_UPDATED: "SIGNATURE_UPDATED",
  SIGNATURE_DEFAULT_UPDATED: "SIGNATURE_DEFAULT_UPDATED",
  SIGNATURE_DELETED: "SIGNATURE_DELETED",
  SIGNATURE_NOT_FOUND: "SIGNATURE_NOT_FOUND",

  MODULE_MASTER: { ID: 401, NAME: "MODULE_MASTER" },
  MODULE_ENTITY: { ID: 401, NAME: "MODULE_ENTITY" },
  MODULE_PERMINSSION: { ID: 401, NAME: "MODULE_PERMINSSION" },
  PRINT_MASTER: { ID: 401, NAME: "PRINT_MASTER" },
  PRINT_PERMISSION: { ID: 401, NAME: "PRINT_PERMISSION" },
  PRINT_TYPE: { ID: 401, NAME: "PRINT_TYPE" },



  ACCOUNT_CATEGORY_MASTER: { ID: 401, NAME: "PRINT_TYPE" },
  NOTIFICAION: { ID: 401, NAME: "NOTIFICAION" },
  TEMPLATE_MESSAGE: { ID: 401, NAME: "TEMPLATE_MESSAGE" },


  LOGIN: { ID: 401, NAME: "LOGIN" },


  APPOINTMENT: { ID: 401, NAME: "APPOINTMENT" },
  LEADS_TYPE: { ID: 401, NAME: "LEADS_TYPE" },
  SALES_ORDER: { ID: 401, NAME: "SALES_ORDER" },
  SALES_ORDER_STOCK: { ID: 401, NAME: "SALES_ORDER_STOCK" },


  DASHBOARD: { ID: 401, NAME: "DASHBOARD" },
  ALLOCATE_BOM: { ID: 401, NAME: "ALLOCATE_BOM" },
  STOCK_ADJUSTMENT: { ID: 401, NAME: "STOCK_ADJUSTMENT" },
  RESERVE_STOCK: { ID: 401, NAME: "RESERVE_STOCK" },
  STOCK: { ID: 401, NAME: "STOCK" },
  SO_BRANCH_PLANING: { ID: 401, NAME: "SO_BRANCH_PLANING" },


  BOM_ITEM_PROCESS: { ID: 401, NAME: "BOM_ITEM_PROCESS" },
  BOM_PRODUCT_PROCESS: { ID: 401, NAME: "BOM_PRODUCT_PROCESS" },
  BOM: { ID: 52, NAME: "BOM" },
  BOM_TRANSACTION: { ID: 401, NAME: "BOM_TRANSACTION" },
  ITEM_BOM_VERSION: { ID: 401, NAME: "ITEM_BOM_VERSION" },


  SUPPLIER_DETAILS: { ID: 401, NAME: "SUPPLIER_DETAILS" },
  SERIAL_NUMBER: { ID: 402, NAME: "Serial Numbers" },

  //Department
  DEPARTMENT_CREATED: "DEPARTMENT_CREATED",
  DEPARTMENT_UPDATED: "DEPARTMENT_UPDATED",
  DEPARTMENT_DELETED: "DEPARTMENT_DELETED",
  DEPARTMENT_NOT_FOUND: "DEPARTMENT_NOT_FOUND",

  // many transactions...
  ATTENDANCE: { ID: 403, NAME: "Attendance" },
};

module.exports = { constants, ENTITIES };