const constants = {
  UPLOAD_PATH: "uploads/",

  ATTENDANCE_FOLDER: "employee/attendance/",
  ATTENDANCE_LOG_FOLDER: "employee/attendance_log/",
  EMPLOYEE_IMG_FOLDER: "employee/images/",

  /* =======================
   * COMMON / GENERIC
   * ======================= */
  SUCCESS: "SUCCESS",
  CREATED: "CREATED",
  UPDATED: "UPDATED",
  DELETED: "DELETED",
  FETCHED: "FETCHED",
  REQUIRED: "REQUIRED",
  NO_RECORDS_FOUND: "NO_RECORDS_FOUND",
  ACTION_SUCCESSFUL: "ACTION_SUCCESSFUL",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  OTP_LIMIT_INFO: "OTP_LIMIT_INFO",
  BLOCKED_NUMBERS_LIST: "BLOCKED_NUMBERS_LIST",
  INTERNAL_DB_ERROR: "INTERNAL_DB_ERROR",

  /* =======================
   * VALIDATION & INPUT
   * ======================= */
  VALIDATION_ERROR: "VALIDATION_ERROR",
  REQUIRED_FIELD_MISSING: "REQUIRED_FIELD_MISSING",
  INVALID_INPUT: "INVALID_INPUT",
  INVALID_ID: "INVALID_ID",
  INVALID_STATUS: "INVALID_STATUS",
  DATE_FORMAT_INVALID: "DATE_FORMAT_INVALID",
  INVALID_FILE_FORMAT: "INVALID_FILE_FORMAT",
  FILE_NOT_FOUND: "FILE_NOT_FOUND",
  SELECT_AT_LEAST_ONE_RECORD: "SELECT_AT_LEAST_ONE_RECORD",
  ATLEAST_ONE_ITEM_REQUIRED: "ATLEAST_ONE_ITEM_REQUIRED",
  AT_LEAST_ONE_TAX: "AT_LEAST_ONE_TAX",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  ACCOUNT_ALREADY_ACTIVE: "ACCOUNT_ALREADY_ACTIVE",



  /* =======================
   * AUTH & PERMISSION
   * ======================= */
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  PASSWORD_MISMATCH: "PASSWORD_MISMATCH",
  OLD_PASSWORD_INCORRECT: "OLD_PASSWORD_INCORRECT",

  /* =======================
  * PERMISSION / MIDDLEWARE
  * ======================= */
  USER_INACTIVE: "USER_INACTIVE",
  NO_PERMISSIONS_ASSIGNED: "NO_PERMISSIONS_ASSIGNED",
  ENTITYNOT_FOUND: "ENTITYNOT_FOUND",
  PERMISSION_CONFIG_MISSING: "PERMISSION_CONFIG_MISSING", // For missing permission types
  COMPANY_OR_BRANCH_MISSING: "COMPANY_OR_BRANCH_MISSING",
  PERMISSION_DENIED_DETAIL: "PERMISSION_DENIED_DETAIL",

  /* =======================
   * RESOURCE / DATA
   * ======================= */
  NOT_FOUND: "NOT_FOUND",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  ALREADY_DELETED: "ALREADY_DELETED",
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",
  FOREIGN_KEY_CONSTRAINT: "FOREIGN_KEY_CONSTRAINT",

  /* =======================
   * DATABASE / SERVER
   * ======================= */
  DATABASE_ERROR: "DATABASE_ERROR",
  TRANSACTION_FAILED: "TRANSACTION_FAILED",
  SERVER_ERROR: "SERVER_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  FAILED_TO_CREATE_RECORD: "FAILED_TO_CREATE_RECORD",
  FAILED_TO_UPDATE_RECORD: "FAILED_TO_UPDATE_RECORD",
  FAILED_TO_DELETE_RECORD: "FAILED_TO_DELETE_RECORD",
  FAILED_TO_CREATE_STOCK: "FAILED_TO_CREATE_STOCK",
  FAILED_TO_UPDATE_STOCK: "FAILED_TO_UPDATE_STOCK",
  FAILED_TO_DELETE_STOCK: "FAILED_TO_DELETE_STOCK",
  FAILED_TO_APPROVE_STOCK: "FAILED_TO_APPROVE_STOCK",
  STOCK_GENERAL_ID_REQUIRED: "STOCK_GENERAL_ID_REQUIRED",
  RESERVE_ADD_STOCK_DELETED: "RESERVE_ADD_STOCK_DELETED",

  /* =======================
   * FILE / UPLOAD
   * ======================= */
  FILE_REQUIRED: "FILE_REQUIRED",
  FILE_TYPE_NOT_ALLOWED: "FILE_TYPE_NOT_ALLOWED",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",

  /* =======================
   * EMAIL
   * ======================= */
  EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",
  EMAIL_AUTH_FAILED: "EMAIL_AUTH_FAILED",
  EMAIL_CONNECTION_FAILED: "EMAIL_CONNECTION_FAILED",
  EMAIL_TIMEOUT: "EMAIL_TIMEOUT",

  /* =======================
   * BUSINESS RULES
   * ======================= */
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  NEGATIVE_STOCK_NOT_ALLOWED: "NEGATIVE_STOCK_NOT_ALLOWED",
  STOCK_NOT_AVAILABLE: "STOCK_NOT_AVAILABLE",
  SERIES_NOT_FOUND: "SERIES_NOT_FOUND",
  SERIES_EXHAUSTED: "SERIES_EXHAUSTED",

  /* =======================
   * ACCOUNTS
   * ======================= */
  RECEIPT_CREATED: "RECEIPT_CREATED",
  RECEIPT_UPDATED: "RECEIPT_UPDATED",
  RECEIPT_DELETED: "RECEIPT_DELETED",
  RECEIPT_NOT_FOUND: "RECEIPT_NOT_FOUND",

  ALLOCATE_BOM_SUCCESS: "ALLOCATE_BOM_SUCCESS",
  ASSIGN_BOM_SUCCESS: "ASSIGN_BOM_SUCCESS",
  SERIAL_NUMBER_FETCHED: "SERIAL_NUMBER_FETCHED",

  CITY_MASTER_CREATED: "CITY_MASTER_CREATED",
  CITY_MASTER_UPDATED: "CITY_MASTER_UPDATED",
  CITY_MASTER_DELETED: "CITY_MASTER_DELETED",
  CITY_MASTER_NOT_FOUND: "CITY_MASTER_NOT_FOUND",

  SO_BRANCH_PLANING_UPDATED: "SO_BRANCH_PLANING_UPDATED",
  SO_BRANCH_PLANING_NOT_FOUND: "SO_BRANCH_PLANING_NOT_FOUND",

  COUNTRY_MASTER_CREATED: "COUNTRY_MASTER_CREATED",
  COUNTRY_MASTER_UPDATED: "COUNTRY_MASTER_UPDATED",
  COUNTRY_MASTER_DELETED: "COUNTRY_MASTER_DELETED",
  COUNTRY_MASTER_NOT_FOUND: "COUNTRY_MASTER_NOT_FOUND",

  STATE_MASTER_CREATED: "STATE_MASTER_CREATED",
  STATE_MASTER_UPDATED: "STATE_MASTER_UPDATED",
  STATE_MASTER_DELETED: "STATE_MASTER_DELETED",
  STATE_MASTER_NOT_FOUND: "STATE_MASTER_NOT_FOUND",

  STOCK_CREATED: "STOCK_CREATED",
  STOCK_UPDATED: "STOCK_UPDATED",
  STOCK_DELETED: "STOCK_DELETED",
  STOCK_NOT_FOUND: "STOCK_NOT_FOUND",

  ZONE_MASTER_CREATED: "ZONE_MASTER_CREATED",
  ZONE_MASTER_UPDATED: "ZONE_MASTER_UPDATED",
  ZONE_MASTER_DELETED: "ZONE_MASTER_DELETED",
  ZONE_MASTER_NOT_FOUND: "ZONE_MASTER_NOT_FOUND",

  CURRENCY_MASTER_CREATED: "CURRENCY_MASTER_CREATED",
  CURRENCY_MASTER_UPDATED: "CURRENCY_MASTER_UPDATED",
  CURRENCY_MASTER_DELETED: "CURRENCY_MASTER_DELETED",
  CURRENCY_MASTER_NOT_FOUND: "CURRENCY_MASTER_NOT_FOUND",

  LOGIN_HISTORY_CREATED: "LOGIN_HISTORY_CREATED",
  LOGIN_HISTORY_UPDATED: "LOGIN_HISTORY_UPDATED",
  LOGIN_HISTORY_DELETED: "LOGIN_HISTORY_DELETED",
  LOGIN_HISTORY_NOT_FOUND: "LOGIN_HISTORY_NOT_FOUND",

  ITEM_SPEC_MASTER_CREATED: "ITEM_SPEC_MASTER_CREATED",
  ITEM_SPEC_MASTER_UPDATED: "ITEM_SPEC_MASTER_UPDATED",
  ITEM_SPEC_MASTER_DELETED: "ITEM_SPEC_MASTER_DELETED",
  ITEM_SPEC_MASTER_NOT_FOUND: "ITEM_SPEC_MASTER_NOT_FOUND",

  ITEM_NAME_PARAMETER_CREATED: "ITEM_NAME_PARAMETER_CREATED",
  ITEM_NAME_PARAMETER_UPDATED: "ITEM_NAME_PARAMETER_UPDATED",
  ITEM_NAME_PARAMETER_DELETED: "ITEM_NAME_PARAMETER_DELETED",
  ITEM_NAME_PARAMETER_NOT_FOUND: "ITEM_NAME_PARAMETER_NOT_FOUND",

  ITEM_TYPE_MASTER_CREATED: "ITEM_TYPE_MASTER_CREATED",
  ITEM_TYPE_MASTER_UPDATED: "ITEM_TYPE_MASTER_UPDATED",
  ITEM_TYPE_MASTER_DELETED: "ITEM_TYPE_MASTER_DELETED",
  ITEM_TYPE_MASTER_NOT_FOUND: "ITEM_TYPE_MASTER_NOT_FOUND",

  PROCESS_LIST_MASTER_CREATED: "PROCESS_LIST_MASTER_CREATED",
  PROCESS_LIST_MASTER_UPDATED: "PROCESS_LIST_MASTER_UPDATED",
  PROCESS_LIST_MASTER_DELETED: "PROCESS_LIST_MASTER_DELETED",
  PROCESS_LIST_MASTER_NOT_FOUND: "PROCESS_LIST_MASTER_NOT_FOUND",

  GODOWN_CREATED: "GODOWN_CREATED",
  GODOWN_UPDATED: "GODOWN_UPDATED",
  GODOWN_DELETED: "GODOWN_DELETED",
  GODOWN_NOT_FOUND: "GODOWN_NOT_FOUND",

  /* =======================
   * ADMINISTRATION
   * ======================= */
    SERIES_CREATED: "SERIES_CREATED",
    SERIES_UPDATED: "SERIES_UPDATED",
    SERIES_DELETED: "SERIES_DELETED",

    TERMS_CREATED: "TERMS_CREATED",
    TERMS_UPDATED: "TERMS_UPDATED",
    TERMS_DELETED: "TERMS_DELETED",

    NOTES_CREATED: "NOTES_CREATED",
    NOTES_UPDATED: "NOTES_UPDATED",
    NOTES_DELETED: "NOTES_DELETED",

    CHARGES_CREATED: "CHARGES_CREATED",
    CHARGES_UPDATED: "CHARGES_UPDATED",
    CHARGES_DELETED: "CHARGES_DELETED",

    TRANSPORT_CREATED: "TRANSPORT_CREATED",
    TRANSPORT_UPDATED: "TRANSPORT_UPDATED",
    TRANSPORT_DELETED: "TRANSPORT_DELETED",

    TAX_GROUP_CREATED: "TAX_GROUP_CREATED",
    TAX_GROUP_UPDATED: "TAX_GROUP_UPDATED",
    TAX_GROUP_DELETED: "TAX_GROUP_DELETED",

    ITEM_CREATED: "ITEM_CREATED",
    ITEM_UPDATED: "ITEM_UPDATED",
    ITEM_DELETED: "ITEM_DELETED",
    ITEM_NOT_FOUND: "ITEM_NOT_FOUND",
    ITEM_EXPORTED: "ITEM_EXPORTED",
    STOCK_RESET_SUCCESS: "STOCK_RESET_SUCCESS",
    INVALID_SERIAL_FORMAT: "INVALID_SERIAL_FORMAT",
    SERIAL_NUMBER_MISMATCH: "SERIAL_NUMBER_MISMATCH",

    CATEGORY_CREATED: "CATEGORY_CREATED",
    CATEGORY_UPDATED: "CATEGORY_UPDATED",
    CATEGORY_DELETED: "CATEGORY_DELETED",
    CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",

    PRINT_MASTER_CREATED: "PRINT_MASTER_CREATED",
    PRINT_MASTER_UPDATED: "PRINT_MASTER_UPDATED",
    PRINT_MASTER_DELETED: "PRINT_MASTER_DELETED",
    PRINT_MASTER_NOT_FOUND: "PRINT_MASTER_NOT_FOUND",

    PRINT_PERMISSION_CREATED: "PRINT_PERMISSION_CREATED",
    PRINT_PERMISSION_UPDATED: "PRINT_PERMISSION_UPDATED",
    PRINT_PERMISSION_DELETED: "PRINT_PERMISSION_DELETED",
    PRINT_PERMISSION_NOT_FOUND: "PRINT_PERMISSION_NOT_FOUND",

    RESERVE_STOCK_CREATED: "RESERVE_STOCK_CREATED",
    RESERVE_STOCK_UPDATED: "RESERVE_STOCK_UPDATED",
    RESERVE_STOCK_DELETED: "RESERVE_STOCK_DELETED",
    RESERVE_STOCK_NOT_FOUND: "RESERVE_STOCK_NOT_FOUND",
    RESERVE_STOCK_FETCHED: "RESERVE_STOCK_FETCHED",

    PRINT_TYPE_MASTER_CREATED: "PRINT_TYPE_MASTER_CREATED",
    PRINT_TYPE_MASTER_UPDATED: "PRINT_TYPE_MASTER_UPDATED",
    PRINT_TYPE_MASTER_DELETED: "PRINT_TYPE_MASTER_DELETED",
    PRINT_TYPE_MASTER_NOT_FOUND: "PRINT_TYPE_MASTER_NOT_FOUND",

    QC_PARAMETER_CREATED: "QC_PARAMETER_CREATED",
    QC_PARAMETER_UPDATED: "QC_PARAMETER_UPDATED",
    QC_PARAMETER_DELETED: "QC_PARAMETER_DELETED",
    QC_PARAMETER_NOT_FOUND: "QC_PARAMETER_NOT_FOUND",

    ITEM_BOM_VERSION_CREATED: "ITEM_BOM_VERSION_CREATED",
    ITEM_BOM_VERSION_UPDATED: "ITEM_BOM_VERSION_UPDATED",
    ITEM_BOM_VERSION_DELETED: "ITEM_BOM_VERSION_DELETED",
    ITEM_BOM_VERSION_NOT_FOUND: "ITEM_BOM_VERSION_NOT_FOUND",

    PRODUCT_BOM_VERSION_CREATED: "PRODUCT_BOM_VERSION_CREATED",
    PRODUCT_BOM_VERSION_UPDATED: "PRODUCT_BOM_VERSION_UPDATED",
    PRODUCT_BOM_VERSION_DELETED: "PRODUCT_BOM_VERSION_DELETED",
    PRODUCT_BOM_VERSION_NOT_FOUND: "PRODUCT_BOM_VERSION_NOT_FOUND",

    QUOTATION_COMPARISON_CREATED: "QUOTATION_COMPARISON_CREATED",
    QUOTATION_COMPARISON_UPDATED: "QUOTATION_COMPARISON_UPDATED",
    QUOTATION_COMPARISON_DELETED: "QUOTATION_COMPARISON_DELETED",
    QUOTATION_COMPARISON_NOT_FOUND: "QUOTATION_COMPARISON_NOT_FOUND",

    SUPPLIER_DETAILS_CREATED: "SUPPLIER_DETAILS_CREATED",
    SUPPLIER_DETAILS_UPDATED: "SUPPLIER_DETAILS_UPDATED",
    SUPPLIER_DETAILS_DELETED: "SUPPLIER_DETAILS_DELETED",
    SUPPLIER_DETAILS_NOT_FOUND: "SUPPLIER_DETAILS_NOT_FOUND",

    INDENT_APPROVAL_CREATED: "INDENT_APPROVAL_CREATED",
    INDENT_APPROVAL_UPDATED: "INDENT_APPROVAL_UPDATED",
    INDENT_APPROVAL_DELETED: "INDENT_APPROVAL_DELETED",
    INDENT_APPROVAL_NOT_FOUND: "INDENT_APPROVAL_NOT_FOUND",

    INDENT_CREATED: "INDENT_CREATED",
    INDENT_UPDATED: "INDENT_UPDATED",
    INDENT_DELETED: "INDENT_DELETED",
    INDENT_NOT_FOUND: "INDENT_NOT_FOUND",

    // Role & Permission
    ROLE_PERMISSION_CREATED: "ROLE_PERMISSION_CREATED",
    ROLE_PERMISSION_UPDATED: "ROLE_PERMISSION_UPDATED",
    ROLE_PERMISSION_DELETED: "ROLE_PERMISSION_DELETED",
    ROLE_PERMISSION_NOT_FOUND: "ROLE_PERMISSION_NOT_FOUND",

    // Company Bank (Accounts)
    COMPANY_BANK_CREATED: "COMPANY_BANK_CREATED",
    COMPANY_BANK_UPDATED: "COMPANY_BANK_UPDATED",
    COMPANY_BANK_DELETED: "COMPANY_BANK_DELETED",
    COMPANY_BANK_NOT_FOUND: "COMPANY_BANK_NOT_FOUND",

    HSN_MASTER_CREATED: "HSN_MASTER_CREATED",
    HSN_MASTER_UPDATED: "HSN_MASTER_UPDATED",
    HSN_MASTER_DELETED: "HSN_MASTER_DELETED",
    HSN_MASTER_NOT_FOUND: "HSN_MASTER_NOT_FOUND",

    // Companies
    COMPANY_CREATED: "COMPANY_CREATED",
    COMPANY_UPDATED: "COMPANY_UPDATED",
    COMPANY_DELETED: "COMPANY_DELETED",
    COMPANY_NOT_FOUND: "COMPANY_NOT_FOUND",

    DRAWING_MASTER_CREATED: "DRAWING_MASTER_CREATED",
    DRAWING_MASTER_UPDATED: "DRAWING_MASTER_UPDATED",
    DRAWING_MASTER_DELETED: "DRAWING_MASTER_DELETED",
    DRAWING_MASTER_NOT_FOUND: "DRAWING_MASTER_NOT_FOUND",

    ITEM_UNIT_MASTER_CREATED: "ITEM_UNIT_MASTER_CREATED",
    ITEM_UNIT_MASTER_UPDATED: "ITEM_UNIT_MASTER_UPDATED",
    ITEM_UNIT_MASTER_DELETED: "ITEM_UNIT_MASTER_DELETED",
    ITEM_UNIT_MASTER_NOT_FOUND: "ITEM_UNIT_MASTER_NOT_FOUND",

    PARTIES_CREATED: "PARTIES_CREATED",
    PARTIES_UPDATED: "PARTIES_UPDATED",
    PARTIES_DELETED: "PARTIES_DELETED",
    PARTIES_NOT_FOUND: "PARTIES_NOT_FOUND",

    COMPANY_SETTING_MASTER_CREATED: "COMPANY_SETTING_MASTER_CREATED",
    COMPANY_SETTING_MASTER_UPDATED: "COMPANY_SETTING_MASTER_UPDATED",
    COMPANY_SETTING_MASTER_DELETED: "COMPANY_SETTING_MASTER_DELETED",
    COMPANY_SETTING_MASTER_NOT_FOUND: "COMPANY_SETTING_MASTER_NOT_FOUND",
    
    TAXES_CREATED: "TAXES_CREATED",
    TAXES_UPDATED: "TAXES_UPDATED",
    TAXES_DELETED: "TAXES_DELETED",
    TAXES_NOT_FOUND: "TAXES_NOT_FOUND",

    // Validation messages
    ACCOUNT_NUMBER_MISMATCH: "ACCOUNT_NUMBER_MISMATCH",

  /* =======================
   * SALSES ENTITY
   * ======================= */
    // Quotation
    QUOTATION_CREATED: "QUOTATION_CREATED",
    QUOTATION_CREATED_SEND_FOR_APPROVAL: "QUOTATION_CREATED_SEND_FOR_APPROVAL",
    QUOTATION_UPDATED: "QUOTATION_UPDATED",
    QUOTATION_DELETED: "QUOTATION_DELETED",
    QUOTATION_NOT_FOUND: "QUOTATION_NOT_FOUND",
    
  /* =======================
   * STOCK ENTITY
   * ======================= */
    STOCK_ADJUSTMENT_CREATED: "STOCK_ADJUSTMENT_CREATED",
    STOCK_ADJUSTMENT_UPDATED: "STOCK_ADJUSTMENT_UPDATED",
    STOCK_ADJUSTMENT_DELETED: "STOCK_ADJUSTMENT_DELETED",
    STOCK_APPROVAL_UPDATED: "STOCK_APPROVAL_UPDATED",

    STOCK_TRANSACTION_FETCHED: "STOCK_TRANSACTION_FETCHED",
    STOCK_DASHBOARD: "STOCK_DASHBOARD",
    STOCK_FETCHED: "STOCK_FETCHED",

   // Company Bank (Accounts)
    BANK_CREATED: "BANK_CREATED",
    BANK_UPDATED: "BANK_UPDATED",
    BANK_DELETED: "BANK_DELETED",
    BANK_NOT_FOUND: "BANK_NOT_FOUND",

  /* =======================
   * STOCK GENERAL CREATED ENTITY
   * ======================= */
  STOCK_GENERAL_CREATED: "STOCK_GENERAL_CREATED",
  STOCK_GENERAL_UPDATED: "STOCK_GENERAL_UPDATED",
  STOCK_GENERAL_DELETED: "STOCK_GENERAL_DELETED",
  STOCK_GENERAL_APPROVAL_UPDATED: "STOCK_GENERAL_APPROVAL_UPDATED",
  STOCK_GENERAL_FETCHED: "STOCK_GENERAL_FETCHED",


  /* =======================
   * BOM (BILL OF MATERIAL) ENTITY
   * ======================= */
  BOM_CREATED: "BOM_CREATED",
  BOM_UPDATED: "BOM_UPDATED",
  BOM_DELETED: "BOM_DELETED",
  BOM_APPROVAL_UPDATED: "BOM_APPROVAL_UPDATED",

  BOM_ITEM_PROCESS_CREATED: "BOM_ITEM_PROCESS_CREATED",
  BOM_ITEM_PROCESS_UPDATED: "BOM_ITEM_PROCESS_UPDATED",
  BOM_ITEM_PROCESS_DELETED: "BOM_ITEM_PROCESS_DELETED",
  BOM_ITEM_PROCESS_FETCHED: "BOM_ITEM_PROCESS_FETCHED",

  BOM_ITEM_PROCESS_APPROVAL_UPDATED: "BOM_ITEM_PROCESS_APPROVAL_UPDATED",

  BOM_PRODUCT_PROCESS_CREATED: "BOM_PRODUCT_PROCESS_CREATED",
  BOM_PRODUCT_PROCESS_UPDATED: "BOM_PRODUCT_PROCESS_UPDATED",
  BOM_PRODUCT_PROCESS_DELETED: "BOM_PRODUCT_PROCESS_DELETED",
  BOM_PRODUCT_PROCESS_FETCHED: "BOM_PRODUCT_PROCESS_FETCHED",

  BOM_PRODUCT_PROCESS_APPROVAL_UPDATED: "BOM_PRODUCT_PROCESS_APPROVAL_UPDATED",

  BOM_TRANSACTION_CREATED: "BOM_TRANSACTION_CREATED",
  BOM_TRANSACTION_UPDATED: "BOM_TRANSACTION_UPDATED",
  BOM_TRANSACTION_DELETED: "BOM_TRANSACTION_DELETED",
  BOM_TRANSACTION_FETCHED: "BOM_TRANSACTION_FETCHED",

  /* =======================
   * SALES
   * ======================= */

  /* =======================
   * USER / COMPANY LIMITS
   * ======================= */
  LIMIT_EXCEEDED: "LIMIT_EXCEEDED",
  USER_LIMIT_REACHED: "USER_LIMIT_REACHED",
  COMPANY_LIMIT_REACHED: "COMPANY_LIMIT_REACHED",

  /* =======================
  * MODULE ENTITY
  * ======================= */
  ENTITY_CREATED: "ENTITY_CREATED",
  ENTITY_UPDATED: "ENTITY_UPDATED",
  ENTITY_DELETED: "ENTITY_DELETED",

  /* =======================
  * MODULE
  * ======================= */
  MODULE_CREATED: "MODULE_CREATED",
  MODULE_UPDATED: "MODULE_UPDATED",
  MODULE_DELETED: "MODULE_DELETED",

  /* =======================
  * MODULE
  * ======================= */
  MODULE_PERMISSION_TYPE_CREATED: "MODULE_PERMISSION_TYPE_CREATED",
  MODULE_PERMISSION_TYPE_UPDATED: "MODULE_PERMISSION_TYPE_UPDATED",
  MODULE_PERMISSION_TYPE_DELETED: "MODULE_PERMISSION_TYPE_DELETED",

  /* =======================
  * MODULE
  * ======================= */
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_DELETED: "USER_DELETED",
};


const ENTITIES = {
    ITEM_MASTER: { ID: 17, NAME: "Item" },
    PARTIES_MASTER: { ID: 27, NAME: "Party" },
    COMPANY_MASTER: { ID: 33, NAME: "Company" },
    BRANCH_MASTER: { ID: 14, NAME: "Branch" },
    USER: { ID: 1, NAME: "User" },
    DRAWING_MASTER: { ID: 37, NAME: "Drawing" },
    PROCESS_LIST_MASTER: { ID: 19, NAME: "ProcessList" },
    RESOURCE_MASTER: { ID: 21, NAME: "Resource" },
    GODOWN: { ID: 48, NAME: "Godown" },

    ITEM_TYPE_MASTER: { ID: 25, NAME: "ItemType" },
    ITEM_CATEGORY: { ID: 15, NAME: "ItemCategory" },
    ITEM_UNIT_MASTER: { ID: 26, NAME: "ItemUnit" },
    ITEM_NAME_PARAMETER: { ID: 8, NAME: "ItemNameParameter" },
    ITEM_SPEC_MASTER: { ID: 12, NAME: "ItemSpecification" },
    ITEM_SPEC_VALUE: { ID: 999, NAME: "ItemSpecificationValue" },
    HSN_MASTER: { ID: 18, NAME: "HSN" },
    QC_PARAMETER: { ID: 20, NAME: "QcParameter" },

    PARTIES_GROUP: { ID: 100, NAME: "PartiesGroup" },
    PARTIES_ADDRESS: { ID: 101, NAME: "PartiesAddress" },
    PARTIES_CONTACT: { ID: 102, NAME: "PartiesContacts" },
    PARTIES_CONSIGNEE: { ID: 103, NAME: "PartiesConsignee" },
    PARTIES_BANK: { ID: 104, NAME: "PartiesBank" },

    SERIES_TYPE: { ID: 105, NAME: "SeriesType" },
    DOCUMENT_MASTER: { ID: 106, NAME: "Document" },
    BUSINESS_TYPE: { ID: 107, NAME: "BusinessType" },
    COMMON_CATEGORY: { ID: 108, NAME: "CommonCategory" },
    PAYMENT_TERMS: { ID: 109, NAME: "PaymentTerms" },
    TRANSPORT_MASTER: { ID: 24, NAME: "Transpotation" },
    BANK_MASTER: { ID: 13, NAME: "Bank" },
    COUNTRY_MASTER: { ID: 110, NAME: "Country" },
    STATE_MASTER: { ID: 111, NAME: "State" },
    CITY_MASTER: { ID: 112, NAME: "City" },
    ZONE_MASTER: { ID: 113, NAME: "Zone" },
    CURRENCY_MASTER: { ID: 16, NAME: "Currency" },
    ROLE_PERMISSION: { ID: 10, NAME: "RolePermission" },

    TAX_TYPE: { ID: 34, NAME: "TaxType" },
    TAX: { ID: 115, NAME: "Taxes" },
    TAX_GROUP: { ID: 35, NAME: "TaxGroup" },
    CHARGES: { ID: 36, NAME: "Charges" },
    TERMS_MASTER: { ID: 23, NAME: "Terms" },

    SALES: { ID: 2, NAME: "Sales" },
    LEADS: { ID: 1, NAME: "leads" },
    QUOTATION: { ID: 3, NAME: "Quotation" },
    PROFORMA: { ID: 41, NAME: "ProformaInvoice" },
    TASK: { ID: 31, NAME: "Task" },

    STOCK_GENERAL: { ID: 55, NAME: "StockGeneral" },
    BATCH_STOCK: { ID: 56, NAME: "BatchStockIn" },

    INVOICE: { ID: 39, NAME: "Invoice" },
    GENERAL_BOOK: { ID: 200, NAME: "GeneralBook" },

    INDENT: { ID: 300, NAME: "Indent" },
    INDENT_APPROVAL: { ID: 300, NAME: "INDENT_APPROVAL" },
    PURCHASE_ORDER: { ID: 38, NAME: "PurchaseOrder" },
    PURCHASE_BILL: { ID: 38, NAME: "PURCHASE_BILL" },
    PURCHASE_QUOTATION: { ID: 38, NAME: "PURCHASE_QUOTATION" },
    QUOTATION_TRANSACTION: { ID: 38, NAME: "QUOTATION_TRANSACTION" },
    QUOTATION_COMPARISON: { ID: 301, NAME: "QuotationComparisonRequest" },

    BOM: { ID: 52, NAME: "BOM" },
    ITEM_BOM_VERSION: { ID: 53, NAME: "ItemBomVersion" },
    PRODUCT_BOM_VERSION: { ID: 54, NAME: "ProductBomVersion" },

    DISPATCH: { ID: 49, NAME: "DeliveryChallan" },

    ACTIVITY_LOG: { ID: 400, NAME: "ActivityLog" },
    LOGIN_HISTORY: { ID: 401, NAME: "LoginHistory" },
    COMPANY_CONFIGRATION: { ID: 401, NAME: "CompanyConfigration" },
    COMPANY_BANK: { ID: 401, NAME: "CompanyBank" },
    STAGE: { ID: 401, NAME: "Stage" },

    SIGNATURE: { ID: 55, NAME: "Signature" },
    SIGNATURE_CREATED: "SIGNATURE_CREATED",
    SIGNATURE_UPDATED: "SIGNATURE_UPDATED",
    SIGNATURE_DEFAULT_UPDATED: "SIGNATURE_DEFAULT_UPDATED",
    SIGNATURE_DELETED: "SIGNATURE_DELETED",
    SIGNATURE_NOT_FOUND: "SIGNATURE_NOT_FOUND",




    MODULE_MASTER: { ID: 401, NAME: "MODULE_MASTER" },
    MODULE_ENTITY: { ID: 401, NAME: "MODULE_ENTITY" },
    MODULE_PERMINSSION: { ID: 401, NAME: "MODULE_PERMINSSION" },
    PRINT_MASTER: { ID: 401, NAME: "PRINT_MASTER" },
    PRINT_PERMISSION: { ID: 401, NAME: "PRINT_PERMISSION" },
    PRINT_TYPE: { ID: 401, NAME: "PRINT_TYPE" },



    ACCOUNT_CATEGORY_MASTER: { ID: 401, NAME: "PRINT_TYPE" },
    NOTIFICAION: { ID: 401, NAME: "NOTIFICAION" },
    TEMPLATE_MESSAGE: { ID: 401, NAME: "TEMPLATE_MESSAGE" },


    LOGIN: { ID: 401, NAME: "LOGIN" },


    APPOINTMENT: { ID: 401, NAME: "APPOINTMENT" },
    LEADS_TYPE: { ID: 401, NAME: "LEADS_TYPE" },
    SALES_ORDER: { ID: 401, NAME: "SALES_ORDER" },
    SALES_ORDER_STOCK: { ID: 401, NAME: "SALES_ORDER_STOCK" },


    DASHBOARD: { ID: 401, NAME: "DASHBOARD" },
    ALLOCATE_BOM: { ID: 401, NAME: "ALLOCATE_BOM" },
    STOCK_ADJUSTMENT: { ID: 401, NAME: "STOCK_ADJUSTMENT" },
    RESERVE_STOCK: { ID: 401, NAME: "RESERVE_STOCK" },
    STOCK: { ID: 401, NAME: "STOCK" },
    SO_BRANCH_PLANING: { ID: 401, NAME: "SO_BRANCH_PLANING" },


    BOM_ITEM_PROCESS: { ID: 401, NAME: "BOM_ITEM_PROCESS" },
    BOM_PRODUCT_PROCESS: { ID: 401, NAME: "BOM_PRODUCT_PROCESS" },
    BOM: { ID: 52, NAME: "BOM" },
    BOM_TRANSACTION: { ID: 401, NAME: "BOM_TRANSACTION" },
    ITEM_BOM_VERSION: { ID: 401, NAME: "ITEM_BOM_VERSION" },


    SUPPLIER_DETAILS: { ID: 401, NAME: "SUPPLIER_DETAILS" },
    SERIAL_NUMBER: { ID: 402, NAME: "Serial Numbers" },

    // many transactions...
};

module.exports = { constants, ENTITIES };